# More option see https://github.com/DreamMaoMao/mango/wiki/

source=./conf/animations.conf
source=./conf/autostart.conf
source=./conf/input.conf
source=./conf/keybinds.conf
source=./conf/layouts.conf
source=./conf/look.conf
source=./conf/misc.conf
source=./conf/monitor.conf
source=./conf/rules.conf


source=~/.config/mango/noctalia.conf
